### ISSUE TITLE
No way to generate relative imports for promoted widgets using `pyuic5`

### ISSUE THREAD

**Issue by stefanseefeld** [baoboa/pyqt5#54]
I'm using `qtcreator` to design the UI of a PyQt application. It allows me to bind custom widgets using "widget promotion". While the UI for this seems to be very C++-centric (the dialog asks to specify a "header file"), the `pyuic5` tool seems to handle it gracefully, i.e. mapping the header filename to a Python module.

However, the generated import statement uses absolute imports ("from widgets import CustomWidget"), and there is no way to instruct it to use relative imports ("from .widgets import CustomWidget"), even when using the `--import-from=.` option.

Am I missing something or is this indeed not possible at present ? (It would be great to make this possible !)

**Comment by baoboa** [comment]
I'm a not able to help you there, please ask this question on the mailing list.
good luck

**Comment by synapticarbors** [comment]
@stefanseefeld -- did you ever determine a solution for this?

**Comment by stefanseefeld** [comment]
Unfortunately I haven't, no.

**Comment by bantamone** [comment]
> Unfortunately I haven't, no.

Sorry to ask these questions, specially if I'm missing the point completely (cause I don't get your problem at all, but there are some things I don't understand):

Promoted widgets like..? QWebEngineView aso? (..or did you write your own?)

You haven't installed PyQt-tools (there's the designer included - or: PySide2, too), because you don't need Creator, Designer would be enough? (..in python/Lib/site-packages/pyqt5_tools/Qt/bin)

Why are you taking this pyuic5-detour and don't import the .ui file with sthg.  like  "uic.loadUi('path/your_filename.ui', self)" (of course: "from PyQt5 import uic")?

Implicit and explicit relative imports in Python 3.x:  [https://www.geeksforgeeks.org/absolute-and-relative-imports-in-python/](https://www.geeksforgeeks.org/absolute-and-relative-imports-in-python)   maybe this helps you a bit?! -- if you are using Py3 at all, cause even this I didn't understand.

[..and still keeps me wondering how this found its way into my mailbox today..]

{..if your post was about the size of your application and the dependencies within Qt5(? you are using, or?) - hey.. write a simple browser without creator/designer, just a few (±30?) lines of code, build a onedir-application with pyinstaller - and even this will be roundabout 230MB of size, and in the directory you'll see why; I don't know who created these links of dependencies within the libs itself, but to reduce this is a tall order..}

**Comment by stefanseefeld** [comment]
Let me try to answer your questions:
* Yes, I have a few custom widgets that I want to reference from the designer
* I don't understand your question about PyQt-tools. How does this relate to my question ?
* I don't want to interpret the .ui file at runtime because that is too limiting
* I'm fully aware of the difference between relative and absolute imports, or otherwise this whole issue wouldn't make any sense, would it. :-)

I have no clue about your mailbox, and don't understand what you are proposing, or why. It doesn't seem relevant to this issue.

**Comment by bantamone** [comment]
thanks.
